-- MySQL Script generated by MySQL Workbench
-- Thu Jul 10 14:50:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sistemarentasdominio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemarentasdominio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemarentasdominio` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
-- -----------------------------------------------------
-- Schema renta_equipos_simple
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema renta_equipos_simple
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `renta_equipos_simple` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `sistemarentasdominio` ;

-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`categorias` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Descripcion` TEXT NULL DEFAULT NULL,
  `TipoCategoria` VARCHAR(50) NULL DEFAULT NULL,
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nombre` (`Nombre` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`subcategorias` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Descripcion` TEXT NULL DEFAULT NULL,
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nombre` (`Nombre` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`categoria_subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`categoria_subcategorias` (
  `CategoriaId` INT NOT NULL,
  `SubcategoriaId` INT NOT NULL,
  PRIMARY KEY (`CategoriaId`, `SubcategoriaId`),
  INDEX `SubcategoriaId` (`SubcategoriaId` ASC) ,
  CONSTRAINT `categoria_subcategorias_ibfk_1`
    FOREIGN KEY (`CategoriaId`)
    REFERENCES `sistemarentasdominio`.`categorias` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `categoria_subcategorias_ibfk_2`
    FOREIGN KEY (`SubcategoriaId`)
    REFERENCES `sistemarentasdominio`.`subcategorias` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`clientes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(200) NOT NULL,
  `RFC` VARCHAR(13) NULL DEFAULT NULL,
  `TelefonoPrincipal` VARCHAR(20) NULL DEFAULT NULL,
  `CorreoElectronico` VARCHAR(100) NULL DEFAULT NULL,
  `TipoCliente` ENUM('Particular', 'Empresa') NULL DEFAULT 'Particular',
  `EstadoCliente` ENUM('Activo', 'Inactivo', 'Prospecto') NULL DEFAULT 'Prospecto',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `RFC` (`RFC` ASC) ,
  UNIQUE INDEX `CorreoElectronico` (`CorreoElectronico` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`cotizaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`cotizaciones` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `FechaCotizacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `FechaValidez` DATE NULL DEFAULT NULL,
  `MontoTotal` DECIMAL(12,2) NULL DEFAULT NULL,
  `EstadoCotizacion` ENUM('Borrador', 'Enviada', 'Aceptada', 'Rechazada', 'Vencida') NULL DEFAULT 'Borrador',
  `TerminosCondiciones` TEXT NULL DEFAULT NULL,
  `NotasInternas` TEXT NULL DEFAULT NULL,
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`cliente_cotizaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`cliente_cotizaciones` (
  `ClienteId` INT NOT NULL,
  `CotizacionId` INT NOT NULL,
  PRIMARY KEY (`ClienteId`, `CotizacionId`),
  INDEX `CotizacionId` (`CotizacionId` ASC) ,
  CONSTRAINT `cliente_cotizaciones_ibfk_1`
    FOREIGN KEY (`ClienteId`)
    REFERENCES `sistemarentasdominio`.`clientes` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `cliente_cotizaciones_ibfk_2`
    FOREIGN KEY (`CotizacionId`)
    REFERENCES `sistemarentasdominio`.`cotizaciones` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`direcciones` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Calle` VARCHAR(255) NOT NULL,
  `NumeroExterior` VARCHAR(20) NULL DEFAULT NULL,
  `NumeroInterior` VARCHAR(20) NULL DEFAULT NULL,
  `Colonia` VARCHAR(100) NULL DEFAULT NULL,
  `Ciudad` VARCHAR(100) NOT NULL,
  `EstadoProvincia` VARCHAR(100) NOT NULL,
  `CodigoPostal` VARCHAR(10) NOT NULL,
  `Pais` VARCHAR(100) NOT NULL,
  `Referencias` TEXT NULL DEFAULT NULL,
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`cliente_direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`cliente_direcciones` (
  `ClienteId` INT NOT NULL,
  `DireccionId` INT NOT NULL,
  `EsPrincipal` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`ClienteId`, `DireccionId`),
  INDEX `DireccionId` (`DireccionId` ASC) ,
  CONSTRAINT `cliente_direcciones_ibfk_1`
    FOREIGN KEY (`ClienteId`)
    REFERENCES `sistemarentasdominio`.`clientes` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `cliente_direcciones_ibfk_2`
    FOREIGN KEY (`DireccionId`)
    REFERENCES `sistemarentasdominio`.`direcciones` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`rentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`rentas` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `FechaInicio` DATETIME NOT NULL,
  `FechaFinPrevista` DATETIME NOT NULL,
  `FechaDevolucionReal` DATETIME NULL DEFAULT NULL,
  `EstadoRenta` ENUM('Programada', 'EnCurso', 'Finalizada', 'Retrasada', 'Cancelada') NULL DEFAULT 'Programada',
  `MontoTotalRenta` DECIMAL(12,2) NULL DEFAULT NULL,
  `DepositoGarantia` DECIMAL(10,2) NULL DEFAULT NULL,
  `Notas` TEXT NULL DEFAULT NULL,
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`cliente_rentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`cliente_rentas` (
  `ClienteId` INT NOT NULL,
  `RentaId` INT NOT NULL,
  PRIMARY KEY (`ClienteId`, `RentaId`),
  INDEX `RentaId` (`RentaId` ASC) ,
  CONSTRAINT `cliente_rentas_ibfk_1`
    FOREIGN KEY (`ClienteId`)
    REFERENCES `sistemarentasdominio`.`clientes` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `cliente_rentas_ibfk_2`
    FOREIGN KEY (`RentaId`)
    REFERENCES `sistemarentasdominio`.`rentas` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`solicitudes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `FechaSolicitud` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `NombreProductoAlternativo` VARCHAR(200) NULL DEFAULT NULL,
  `CantidadSolicitada` INT NULL DEFAULT '1',
  `DescripcionNecesidad` TEXT NULL DEFAULT NULL,
  `EstadoSolicitud` ENUM('Nueva', 'EnProceso', 'Atendida', 'Cancelada') NULL DEFAULT 'Nueva',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`cliente_solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`cliente_solicitudes` (
  `ClienteId` INT NOT NULL,
  `SolicitudId` INT NOT NULL,
  PRIMARY KEY (`ClienteId`, `SolicitudId`),
  INDEX `SolicitudId` (`SolicitudId` ASC) ,
  CONSTRAINT `cliente_solicitudes_ibfk_1`
    FOREIGN KEY (`ClienteId`)
    REFERENCES `sistemarentasdominio`.`clientes` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `cliente_solicitudes_ibfk_2`
    FOREIGN KEY (`SolicitudId`)
    REFERENCES `sistemarentasdominio`.`solicitudes` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`detallescotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`detallescotizacion` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `DescripcionItem` VARCHAR(255) NULL DEFAULT NULL,
  `Cantidad` INT NOT NULL,
  `PrecioUnitario` DECIMAL(10,2) NOT NULL,
  `Subtotal` DECIMAL(10,2) GENERATED ALWAYS AS ((`Cantidad` * `PrecioUnitario`)) STORED,
  `DescuentoPorcentaje` DECIMAL(5,2) NULL DEFAULT '0.00',
  `ImpuestosAplicables` DECIMAL(10,2) NULL DEFAULT NULL,
  `Notas` TEXT NULL DEFAULT NULL,
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`cotizacion_detallescotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`cotizacion_detallescotizacion` (
  `CotizacionId` INT NOT NULL,
  `DetalleCotizacionId` INT NOT NULL,
  PRIMARY KEY (`CotizacionId`, `DetalleCotizacionId`),
  INDEX `DetalleCotizacionId` (`DetalleCotizacionId` ASC) ,
  CONSTRAINT `cotizacion_detallescotizacion_ibfk_1`
    FOREIGN KEY (`CotizacionId`)
    REFERENCES `sistemarentasdominio`.`cotizaciones` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `cotizacion_detallescotizacion_ibfk_2`
    FOREIGN KEY (`DetalleCotizacionId`)
    REFERENCES `sistemarentasdominio`.`detallescotizacion` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`cotizacion_rentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`cotizacion_rentas` (
  `CotizacionId` INT NOT NULL,
  `RentaId` INT NOT NULL,
  PRIMARY KEY (`CotizacionId`, `RentaId`),
  INDEX `RentaId` (`RentaId` ASC) ,
  CONSTRAINT `cotizacion_rentas_ibfk_1`
    FOREIGN KEY (`CotizacionId`)
    REFERENCES `sistemarentasdominio`.`cotizaciones` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `cotizacion_rentas_ibfk_2`
    FOREIGN KEY (`RentaId`)
    REFERENCES `sistemarentasdominio`.`rentas` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`productos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) NOT NULL,
  `Descripcion` TEXT NULL DEFAULT NULL,
  `Marca` VARCHAR(100) NULL DEFAULT NULL,
  `Modelo` VARCHAR(100) NULL DEFAULT NULL,
  `PrecioReferenciaRenta` DECIMAL(10,2) NULL DEFAULT NULL,
  `SKU` VARCHAR(50) NULL DEFAULT NULL,
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `SKU` (`SKU` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`detallecotizacion_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`detallecotizacion_productos` (
  `DetalleCotizacionId` INT NOT NULL,
  `ProductoId` INT NOT NULL,
  PRIMARY KEY (`DetalleCotizacionId`, `ProductoId`),
  INDEX `ProductoId` (`ProductoId` ASC) ,
  CONSTRAINT `detallecotizacion_productos_ibfk_1`
    FOREIGN KEY (`DetalleCotizacionId`)
    REFERENCES `sistemarentasdominio`.`detallescotizacion` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `detallecotizacion_productos_ibfk_2`
    FOREIGN KEY (`ProductoId`)
    REFERENCES `sistemarentasdominio`.`productos` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`detallesrenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`detallesrenta` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `PrecioRentaItem` DECIMAL(10,2) NOT NULL,
  `CondicionSalida` TEXT NULL DEFAULT NULL,
  `CondicionRegreso` TEXT NULL DEFAULT NULL,
  `Notas` TEXT NULL DEFAULT NULL,
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`inventarioitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`inventarioitems` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `NumeroSerie` VARCHAR(100) NULL DEFAULT NULL,
  `EstadoItem` ENUM('Disponible', 'Rentado', 'EnMantenimiento', 'DeBaja') NOT NULL DEFAULT 'Disponible',
  `FechaAdquisicion` DATE NULL DEFAULT NULL,
  `CostoAdquisicion` DECIMAL(10,2) NULL DEFAULT NULL,
  `UbicacionFisica` VARCHAR(100) NULL DEFAULT NULL,
  `Notas` TEXT NULL DEFAULT NULL,
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `NumeroSerie` (`NumeroSerie` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`detallerenta_inventarioitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`detallerenta_inventarioitems` (
  `DetalleRentaId` INT NOT NULL,
  `InventarioItemId` INT NOT NULL,
  PRIMARY KEY (`DetalleRentaId`, `InventarioItemId`),
  INDEX `InventarioItemId` (`InventarioItemId` ASC) ,
  CONSTRAINT `detallerenta_inventarioitems_ibfk_1`
    FOREIGN KEY (`DetalleRentaId`)
    REFERENCES `sistemarentasdominio`.`detallesrenta` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `detallerenta_inventarioitems_ibfk_2`
    FOREIGN KEY (`InventarioItemId`)
    REFERENCES `sistemarentasdominio`.`inventarioitems` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`devoluciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`devoluciones` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `FechaDevolucionProgramada` DATE NULL DEFAULT NULL,
  `FechaDevolucionReal` DATETIME NULL DEFAULT NULL,
  `EstadoDevolucion` ENUM('Pendiente', 'EnProcesoInspeccion', 'Completa', 'IncompletaConProblemas') NULL DEFAULT 'Pendiente',
  `PersonaRecibe` VARCHAR(150) NULL DEFAULT NULL,
  `NotasGenerales` TEXT NULL DEFAULT NULL,
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`devolucion_inventarioitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`devolucion_inventarioitems` (
  `DevolucionId` INT NOT NULL,
  `InventarioItemId` INT NOT NULL,
  `CondicionAlRegresar` TEXT NULL DEFAULT NULL,
  `RequiereMantenimiento` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`DevolucionId`, `InventarioItemId`),
  INDEX `InventarioItemId` (`InventarioItemId` ASC) ,
  CONSTRAINT `devolucion_inventarioitems_ibfk_1`
    FOREIGN KEY (`DevolucionId`)
    REFERENCES `sistemarentasdominio`.`devoluciones` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `devolucion_inventarioitems_ibfk_2`
    FOREIGN KEY (`InventarioItemId`)
    REFERENCES `sistemarentasdominio`.`inventarioitems` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`mantenimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`mantenimientos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `FechaInicio` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `FechaFinPrevista` DATE NULL DEFAULT NULL,
  `FechaFinReal` DATE NULL DEFAULT NULL,
  `TipoMantenimiento` ENUM('Preventivo', 'Correctivo', 'Mejora') NULL DEFAULT 'Correctivo',
  `DescripcionProblema` TEXT NULL DEFAULT NULL,
  `DescripcionTrabajoRealizado` TEXT NULL DEFAULT NULL,
  `CostoEstimado` DECIMAL(10,2) NULL DEFAULT NULL,
  `CostoReal` DECIMAL(10,2) NULL DEFAULT NULL,
  `EstadoMantenimiento` ENUM('Programado', 'EnProceso', 'Finalizado', 'Cancelado') NULL DEFAULT 'Programado',
  `Responsable` VARCHAR(150) NULL DEFAULT NULL,
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`devolucionitem_mantenimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`devolucionitem_mantenimientos` (
  `DevolucionId` INT NOT NULL,
  `InventarioItemId` INT NOT NULL,
  `MantenimientoId` INT NOT NULL,
  PRIMARY KEY (`DevolucionId`, `InventarioItemId`, `MantenimientoId`),
  INDEX `InventarioItemId` (`InventarioItemId` ASC) ,
  INDEX `MantenimientoId` (`MantenimientoId` ASC) ,
  CONSTRAINT `devolucionitem_mantenimientos_ibfk_1`
    FOREIGN KEY (`DevolucionId`)
    REFERENCES `sistemarentasdominio`.`devoluciones` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `devolucionitem_mantenimientos_ibfk_2`
    FOREIGN KEY (`InventarioItemId`)
    REFERENCES `sistemarentasdominio`.`inventarioitems` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `devolucionitem_mantenimientos_ibfk_3`
    FOREIGN KEY (`MantenimientoId`)
    REFERENCES `sistemarentasdominio`.`mantenimientos` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`entregas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`entregas` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `FechaEnvio` DATETIME NULL DEFAULT NULL,
  `CompaniaEnvio` VARCHAR(100) NULL DEFAULT NULL,
  `NumeroGuia` VARCHAR(100) NULL DEFAULT NULL,
  `EstadoEntrega` ENUM('Programada', 'EnTransito', 'Entregada', 'Fallida') NULL DEFAULT 'Programada',
  `Notas` TEXT NULL DEFAULT NULL,
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`entrega_direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`entrega_direcciones` (
  `EntregaId` INT NOT NULL,
  `DireccionId` INT NOT NULL,
  PRIMARY KEY (`EntregaId`, `DireccionId`),
  INDEX `DireccionId` (`DireccionId` ASC) ,
  CONSTRAINT `entrega_direcciones_ibfk_1`
    FOREIGN KEY (`EntregaId`)
    REFERENCES `sistemarentasdominio`.`entregas` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `entrega_direcciones_ibfk_2`
    FOREIGN KEY (`DireccionId`)
    REFERENCES `sistemarentasdominio`.`direcciones` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`entrega_inventarioitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`entrega_inventarioitems` (
  `EntregaId` INT NOT NULL,
  `InventarioItemId` INT NOT NULL,
  PRIMARY KEY (`EntregaId`, `InventarioItemId`),
  INDEX `InventarioItemId` (`InventarioItemId` ASC) ,
  CONSTRAINT `entrega_inventarioitems_ibfk_1`
    FOREIGN KEY (`EntregaId`)
    REFERENCES `sistemarentasdominio`.`entregas` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `entrega_inventarioitems_ibfk_2`
    FOREIGN KEY (`InventarioItemId`)
    REFERENCES `sistemarentasdominio`.`inventarioitems` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`inventarioitem_mantenimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`inventarioitem_mantenimientos` (
  `InventarioItemId` INT NOT NULL,
  `MantenimientoId` INT NOT NULL,
  PRIMARY KEY (`InventarioItemId`, `MantenimientoId`),
  INDEX `MantenimientoId` (`MantenimientoId` ASC) ,
  CONSTRAINT `inventarioitem_mantenimientos_ibfk_1`
    FOREIGN KEY (`InventarioItemId`)
    REFERENCES `sistemarentasdominio`.`inventarioitems` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `inventarioitem_mantenimientos_ibfk_2`
    FOREIGN KEY (`MantenimientoId`)
    REFERENCES `sistemarentasdominio`.`mantenimientos` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`producto_inventarioitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`producto_inventarioitems` (
  `ProductoId` INT NOT NULL,
  `InventarioItemId` INT NOT NULL,
  PRIMARY KEY (`ProductoId`, `InventarioItemId`),
  INDEX `InventarioItemId` (`InventarioItemId` ASC) ,
  CONSTRAINT `producto_inventarioitems_ibfk_1`
    FOREIGN KEY (`ProductoId`)
    REFERENCES `sistemarentasdominio`.`productos` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `producto_inventarioitems_ibfk_2`
    FOREIGN KEY (`InventarioItemId`)
    REFERENCES `sistemarentasdominio`.`inventarioitems` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`proveedores` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `NombreEmpresa` VARCHAR(200) NOT NULL,
  `RFC` VARCHAR(13) NULL DEFAULT NULL,
  `NombreContacto` VARCHAR(150) NULL DEFAULT NULL,
  `TelefonoContacto` VARCHAR(20) NULL DEFAULT NULL,
  `CorreoContacto` VARCHAR(100) NULL DEFAULT NULL,
  `EstadoProveedor` ENUM('Activo', 'Inactivo') NULL DEFAULT 'Activo',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `NombreEmpresa` (`NombreEmpresa` ASC) ,
  UNIQUE INDEX `RFC` (`RFC` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`proveedor_cotizaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`proveedor_cotizaciones` (
  `ProveedorId` INT NOT NULL,
  `CotizacionId` INT NOT NULL,
  PRIMARY KEY (`ProveedorId`, `CotizacionId`),
  INDEX `CotizacionId` (`CotizacionId` ASC) ,
  CONSTRAINT `proveedor_cotizaciones_ibfk_1`
    FOREIGN KEY (`ProveedorId`)
    REFERENCES `sistemarentasdominio`.`proveedores` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `proveedor_cotizaciones_ibfk_2`
    FOREIGN KEY (`CotizacionId`)
    REFERENCES `sistemarentasdominio`.`cotizaciones` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`proveedor_direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`proveedor_direcciones` (
  `ProveedorId` INT NOT NULL,
  `DireccionId` INT NOT NULL,
  `EsPrincipal` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`ProveedorId`, `DireccionId`),
  INDEX `DireccionId` (`DireccionId` ASC) ,
  CONSTRAINT `proveedor_direcciones_ibfk_1`
    FOREIGN KEY (`ProveedorId`)
    REFERENCES `sistemarentasdominio`.`proveedores` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `proveedor_direcciones_ibfk_2`
    FOREIGN KEY (`DireccionId`)
    REFERENCES `sistemarentasdominio`.`direcciones` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`renta_detallesrenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`renta_detallesrenta` (
  `RentaId` INT NOT NULL,
  `DetalleRentaId` INT NOT NULL,
  PRIMARY KEY (`RentaId`, `DetalleRentaId`),
  INDEX `DetalleRentaId` (`DetalleRentaId` ASC) ,
  CONSTRAINT `renta_detallesrenta_ibfk_1`
    FOREIGN KEY (`RentaId`)
    REFERENCES `sistemarentasdominio`.`rentas` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `renta_detallesrenta_ibfk_2`
    FOREIGN KEY (`DetalleRentaId`)
    REFERENCES `sistemarentasdominio`.`detallesrenta` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`renta_devoluciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`renta_devoluciones` (
  `RentaId` INT NOT NULL,
  `DevolucionId` INT NOT NULL,
  PRIMARY KEY (`RentaId`, `DevolucionId`),
  INDEX `DevolucionId` (`DevolucionId` ASC) ,
  CONSTRAINT `renta_devoluciones_ibfk_1`
    FOREIGN KEY (`RentaId`)
    REFERENCES `sistemarentasdominio`.`rentas` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `renta_devoluciones_ibfk_2`
    FOREIGN KEY (`DevolucionId`)
    REFERENCES `sistemarentasdominio`.`devoluciones` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`renta_entregas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`renta_entregas` (
  `RentaId` INT NOT NULL,
  `EntregaId` INT NOT NULL,
  PRIMARY KEY (`RentaId`, `EntregaId`),
  INDEX `EntregaId` (`EntregaId` ASC) ,
  CONSTRAINT `renta_entregas_ibfk_1`
    FOREIGN KEY (`RentaId`)
    REFERENCES `sistemarentasdominio`.`rentas` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `renta_entregas_ibfk_2`
    FOREIGN KEY (`EntregaId`)
    REFERENCES `sistemarentasdominio`.`entregas` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`roles` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(50) NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Descripcion` TEXT NULL DEFAULT NULL,
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Codigo` (`Codigo` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`solicitud_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`solicitud_categorias` (
  `SolicitudId` INT NOT NULL,
  `CategoriaId` INT NOT NULL,
  PRIMARY KEY (`SolicitudId`, `CategoriaId`),
  INDEX `CategoriaId` (`CategoriaId` ASC) ,
  CONSTRAINT `solicitud_categorias_ibfk_1`
    FOREIGN KEY (`SolicitudId`)
    REFERENCES `sistemarentasdominio`.`solicitudes` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `solicitud_categorias_ibfk_2`
    FOREIGN KEY (`CategoriaId`)
    REFERENCES `sistemarentasdominio`.`categorias` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`solicitud_cotizaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`solicitud_cotizaciones` (
  `SolicitudId` INT NOT NULL,
  `CotizacionId` INT NOT NULL,
  PRIMARY KEY (`SolicitudId`, `CotizacionId`),
  INDEX `CotizacionId` (`CotizacionId` ASC) ,
  CONSTRAINT `solicitud_cotizaciones_ibfk_1`
    FOREIGN KEY (`SolicitudId`)
    REFERENCES `sistemarentasdominio`.`solicitudes` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `solicitud_cotizaciones_ibfk_2`
    FOREIGN KEY (`CotizacionId`)
    REFERENCES `sistemarentasdominio`.`cotizaciones` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`solicitud_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`solicitud_productos` (
  `SolicitudId` INT NOT NULL,
  `ProductoId` INT NOT NULL,
  PRIMARY KEY (`SolicitudId`, `ProductoId`),
  INDEX `ProductoId` (`ProductoId` ASC) ,
  CONSTRAINT `solicitud_productos_ibfk_1`
    FOREIGN KEY (`SolicitudId`)
    REFERENCES `sistemarentasdominio`.`solicitudes` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `solicitud_productos_ibfk_2`
    FOREIGN KEY (`ProductoId`)
    REFERENCES `sistemarentasdominio`.`productos` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`solicitud_subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`solicitud_subcategorias` (
  `SolicitudId` INT NOT NULL,
  `SubcategoriaId` INT NOT NULL,
  PRIMARY KEY (`SolicitudId`, `SubcategoriaId`),
  INDEX `SubcategoriaId` (`SubcategoriaId` ASC) ,
  CONSTRAINT `solicitud_subcategorias_ibfk_1`
    FOREIGN KEY (`SolicitudId`)
    REFERENCES `sistemarentasdominio`.`solicitudes` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `solicitud_subcategorias_ibfk_2`
    FOREIGN KEY (`SubcategoriaId`)
    REFERENCES `sistemarentasdominio`.`subcategorias` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`subcategoria_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`subcategoria_productos` (
  `SubcategoriaId` INT NOT NULL,
  `ProductoId` INT NOT NULL,
  PRIMARY KEY (`SubcategoriaId`, `ProductoId`),
  INDEX `ProductoId` (`ProductoId` ASC) ,
  CONSTRAINT `subcategoria_productos_ibfk_1`
    FOREIGN KEY (`SubcategoriaId`)
    REFERENCES `sistemarentasdominio`.`subcategorias` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `subcategoria_productos_ibfk_2`
    FOREIGN KEY (`ProductoId`)
    REFERENCES `sistemarentasdominio`.`productos` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`usuarios` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `NombreUsuario` VARCHAR(100) NOT NULL,
  `PasswordHash` VARCHAR(255) NOT NULL,
  `NombreCompleto` VARCHAR(200) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(20) NULL DEFAULT NULL,
  `Departamento` VARCHAR(100) NULL DEFAULT NULL,
  `Estado` ENUM('Activo', 'Inactivo', 'Bloqueado') NULL DEFAULT 'Activo',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `NombreUsuario` (`NombreUsuario` ASC) ,
  UNIQUE INDEX `Email` (`Email` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`usuario_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`usuario_roles` (
  `UsuarioId` INT NOT NULL,
  `RolId` INT NOT NULL,
  PRIMARY KEY (`UsuarioId`, `RolId`),
  INDEX `RolId` (`RolId` ASC) ,
  CONSTRAINT `usuario_roles_ibfk_1`
    FOREIGN KEY (`UsuarioId`)
    REFERENCES `sistemarentasdominio`.`usuarios` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `usuario_roles_ibfk_2`
    FOREIGN KEY (`RolId`)
    REFERENCES `sistemarentasdominio`.`roles` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

USE `renta_equipos_simple` ;

-- -----------------------------------------------------
-- Table `renta_equipos_simple`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renta_equipos_simple`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificacion del cliente',
  `nombre` VARCHAR(200) NOT NULL COMMENT 'Nombre del cliente',
  `email` VARCHAR(100) NULL DEFAULT NULL COMMENT 'correo del cliente',
  `telefono` VARCHAR(20) NOT NULL COMMENT 'Telefono del cliente',
  `direccion` TEXT NULL DEFAULT NULL COMMENT 'Direccion del cliente',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `renta_equipos_simple`.`equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renta_equipos_simple`.`equipos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificacion del equipo',
  `nombre` VARCHAR(150) NOT NULL COMMENT 'Nombre del equipo',
  `numero_serie` VARCHAR(100) NOT NULL COMMENT 'Numero de serie',
  `descripcion` TEXT NULL DEFAULT NULL COMMENT 'Descripcion',
  `estado` ENUM('Disponible', 'Rentado', 'En Mantenimiento', 'De Baja') NOT NULL DEFAULT 'Disponible' COMMENT 'Estado',
  `precio_renta_dia` DECIMAL(10,2) NOT NULL COMMENT 'Precio de la renta al dia',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `numero_serie_UNIQUE` (`numero_serie` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `renta_equipos_simple`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renta_equipos_simple`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificacion del rol',
  `nombre` VARCHAR(100) NOT NULL COMMENT 'Nombre del rol',
  `descripcion` TEXT NULL DEFAULT NULL COMMENT 'Descripcion del rol',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `renta_equipos_simple`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renta_equipos_simple`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificacion del usuario',
  `nombre_completo` VARCHAR(200) NOT NULL COMMENT 'Nombre completo del usuario',
  `email` VARCHAR(100) NOT NULL COMMENT 'Correo del usuario',
  `password_hash` VARCHAR(255) NOT NULL COMMENT 'Contraseña como una cadena única de caracteres',
  `estado` ENUM('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo' COMMENT 'Estado del usuario',
  `rol_id` INT NOT NULL COMMENT 'Identificacion del rol',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `fk_usuarios_roles_idx` (`rol_id` ASC) ,
  CONSTRAINT `fk_usuarios_roles`
    FOREIGN KEY (`rol_id`)
    REFERENCES `renta_equipos_simple`.`roles` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `renta_equipos_simple`.`mantenimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renta_equipos_simple`.`mantenimientos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificacion del mantenimiento',
  `equipo_id` INT NOT NULL COMMENT 'Identifcacion del equipo',
  `usuario_id` INT NULL DEFAULT NULL COMMENT 'Identifiacion del usuario',
  `fecha_inicio` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de inicio',
  `fecha_fin` DATETIME NULL DEFAULT NULL COMMENT 'Fecha de fin',
  `descripcion_problema` TEXT NOT NULL COMMENT 'Descripcion del problema',
  `trabajo_realizado` TEXT NULL DEFAULT NULL COMMENT 'Trabajo Realizado',
  `costo` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT 'Costo del mantenimiento',
  `estado_mantenimiento` ENUM('Programado', 'En Proceso', 'Finalizado') NOT NULL DEFAULT 'Programado' COMMENT 'Estado del mantenimiento',
  PRIMARY KEY (`id`),
  INDEX `fk_mantenimientos_equipos_idx` (`equipo_id` ASC) ,
  INDEX `fk_mantenimientos_usuarios_idx` (`usuario_id` ASC) ,
  CONSTRAINT `fk_mantenimientos_equipos`
    FOREIGN KEY (`equipo_id`)
    REFERENCES `renta_equipos_simple`.`equipos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_mantenimientos_usuarios`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `renta_equipos_simple`.`usuarios` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `renta_equipos_simple`.`rentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renta_equipos_simple`.`rentas` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificacion de la renta',
  `equipo_id` INT NOT NULL COMMENT 'Identificacion del equipo',
  `cliente_id` INT NOT NULL COMMENT 'Identificacion del cliente',
  `usuario_id` INT NOT NULL COMMENT 'Identifiacion del usuario',
  `fecha_inicio` DATETIME NOT NULL COMMENT 'Fecha de inicio',
  `fecha_fin_prevista` DATETIME NOT NULL COMMENT 'Fecha de fin prevista',
  `fecha_devolucion_real` DATETIME NULL DEFAULT NULL COMMENT 'Fecha de la devolucion real',
  `monto_total` DECIMAL(12,2) NOT NULL COMMENT 'Monto total',
  `estado_renta` ENUM('Programada', 'En Curso', 'Finalizada', 'Retrasada') NOT NULL DEFAULT 'Programada' COMMENT 'Estado Renta',
  PRIMARY KEY (`id`),
  INDEX `fk_rentas_equipos_idx` (`equipo_id` ASC) ,
  INDEX `fk_rentas_clientes_idx` (`cliente_id` ASC) ,
  INDEX `fk_rentas_usuarios_idx` (`usuario_id` ASC) ,
  CONSTRAINT `fk_rentas_clientes`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `renta_equipos_simple`.`clientes` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rentas_equipos`
    FOREIGN KEY (`equipo_id`)
    REFERENCES `renta_equipos_simple`.`equipos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rentas_usuarios`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `renta_equipos_simple`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
