-- MySQL Script generated by MySQL Workbench
-- Thu May 29 17:28:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sistemarentasdominio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemarentasdominio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemarentasdominio` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `sistemarentasdominio` ;

-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`categorias` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificacion de la categoria',
  `Nombre` VARCHAR(100) NOT NULL COMMENT 'Nombre de la categoria',
  `Descripcion` TEXT NULL DEFAULT NULL COMMENT 'Descripcion de la categoria',
  `TipoCategoria` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Tipo de la categoria',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion de la categoria',
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de actualizacion de la categoria',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nombre` (`Nombre` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`subcategorias` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificacion de la subcategoria',
  `Nombre` VARCHAR(100) NOT NULL COMMENT 'Nombre de la subcategoria',
  `Descripcion` TEXT NULL DEFAULT NULL COMMENT 'Descripcion de la subcategoria',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion de la subcategoria',
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de actualizacion de la subcategoria',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nombre` (`Nombre` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`categoria_subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`categoria_subcategorias` (
  `CategoriaId` INT NOT NULL COMMENT 'Identificacion de la categoria ',
  `SubcategoriaId` INT NOT NULL COMMENT 'Identificacion de la subcategoria',
  PRIMARY KEY (`CategoriaId`, `SubcategoriaId`),
  INDEX `SubcategoriaId` (`SubcategoriaId` ASC) ,
  CONSTRAINT `categoria_subcategorias_ibfk_1`
    FOREIGN KEY (`CategoriaId`)
    REFERENCES `sistemarentasdominio`.`categorias` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `categoria_subcategorias_ibfk_2`
    FOREIGN KEY (`SubcategoriaId`)
    REFERENCES `sistemarentasdominio`.`subcategorias` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`clientes` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identifiacion del cliente',
  `Nombre` VARCHAR(200) NOT NULL COMMENT 'Nombre del cliente',
  `RFC` VARCHAR(13) NULL DEFAULT NULL COMMENT 'Registro Único Tributario del cliente',
  `TelefonoPrincipal` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Telefono principal del cliente',
  `CorreoElectronico` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Correo electronico del cliente',
  `TipoCliente` ENUM('Particular', 'Empresa') NULL DEFAULT 'Particular' COMMENT 'Tipo de cliente',
  `EstadoCliente` ENUM('Activo', 'Inactivo', 'Prospecto') NULL DEFAULT 'Prospecto' COMMENT 'Estado del cliente',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion del cliente',
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de actualizacion del cliente',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `RFC` (`RFC` ASC) ,
  UNIQUE INDEX `CorreoElectronico` (`CorreoElectronico` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`cotizaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`cotizaciones` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identifiacion de la cotizacion',
  `FechaCotizacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de la cotizacion',
  `FechaValidez` DATE NULL DEFAULT NULL COMMENT 'Fecha de validez de la cotizacion',
  `MontoTotal` DECIMAL(12,2) NULL DEFAULT NULL COMMENT 'Monto total de la cotizacion',
  `EstadoCotizacion` ENUM('Borrador', 'Enviada', 'Aceptada', 'Rechazada', 'Vencida') NULL DEFAULT 'Borrador' COMMENT 'Estado de la cotizacion',
  `TerminosCondiciones` TEXT NULL DEFAULT NULL COMMENT 'Terminos de condiciones de la cotizacion',
  `NotasInternas` TEXT NULL DEFAULT NULL COMMENT 'Notas internas de la cotizacion',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion de la cotizacion',
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de actualizacion de la cotizacion',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`cliente_cotizaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`cliente_cotizaciones` (
  `ClienteId` INT NOT NULL COMMENT 'Identificacion del cliente',
  `CotizacionId` INT NOT NULL COMMENT 'Identifiacion de la cotizacion',
  PRIMARY KEY (`ClienteId`, `CotizacionId`),
  INDEX `CotizacionId` (`CotizacionId` ASC) ,
  CONSTRAINT `cliente_cotizaciones_ibfk_1`
    FOREIGN KEY (`ClienteId`)
    REFERENCES `sistemarentasdominio`.`clientes` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `cliente_cotizaciones_ibfk_2`
    FOREIGN KEY (`CotizacionId`)
    REFERENCES `sistemarentasdominio`.`cotizaciones` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`direcciones` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificacion de la direccion',
  `Calle` VARCHAR(255) NOT NULL COMMENT 'Calle de la direccion',
  `NumeroExterior` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Numero exterior de la direccion',
  `NumeroInterior` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Numero interior de la direccion',
  `Colonia` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Colonia de la direccion',
  `Ciudad` VARCHAR(100) NOT NULL COMMENT 'Ciudad de la direccion',
  `EstadoProvincia` VARCHAR(100) NOT NULL COMMENT 'Estado o  provincia de la direccion',
  `CodigoPostal` VARCHAR(10) NOT NULL COMMENT 'Codigo postal de la direccion',
  `Pais` VARCHAR(100) NOT NULL COMMENT 'Pais de la direccion',
  `Referencias` TEXT NULL DEFAULT NULL COMMENT 'Referencia de la direccion',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion de la direccion',
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de actualizacion de la direccion',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`cliente_direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`cliente_direcciones` (
  `ClienteId` INT NOT NULL COMMENT 'Identificacion del cliente',
  `DireccionId` INT NOT NULL COMMENT 'Identificacion de la direccion',
  `EsPrincipal` TINYINT(1) NULL DEFAULT '1' COMMENT 'Principal de la direccion',
  PRIMARY KEY (`ClienteId`, `DireccionId`),
  INDEX `DireccionId` (`DireccionId` ASC) ,
  CONSTRAINT `cliente_direcciones_ibfk_1`
    FOREIGN KEY (`ClienteId`)
    REFERENCES `sistemarentasdominio`.`clientes` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `cliente_direcciones_ibfk_2`
    FOREIGN KEY (`DireccionId`)
    REFERENCES `sistemarentasdominio`.`direcciones` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`rentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`rentas` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificacion de la renta ',
  `FechaInicio` DATETIME NOT NULL COMMENT 'Fecha de inicio de la renta',
  `FechaFinPrevista` DATETIME NOT NULL COMMENT 'Fecha de fin previsto de la renta ',
  `FechaDevolucionReal` DATETIME NULL DEFAULT NULL COMMENT 'Fecha de devolucion real de la renta',
  `EstadoRenta` ENUM('Programada', 'EnCurso', 'Finalizada', 'Retrasada', 'Cancelada') NULL DEFAULT 'Programada' COMMENT 'Estado de la renta',
  `MontoTotalRenta` DECIMAL(12,2) NULL DEFAULT NULL COMMENT 'Monto total de la renta',
  `DepositoGarantia` DECIMAL(10,2) NULL DEFAULT NULL COMMENT 'Deposito de garantia de la renta',
  `Notas` TEXT NULL DEFAULT NULL COMMENT 'Notas de la renta',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion de la renta',
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de actualizacion de la renta',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`cliente_rentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`cliente_rentas` (
  `ClienteId` INT NOT NULL COMMENT 'Identificacion del cliente',
  `RentaId` INT NOT NULL COMMENT 'Identificacion de la renta',
  PRIMARY KEY (`ClienteId`, `RentaId`),
  INDEX `RentaId` (`RentaId` ASC) ,
  CONSTRAINT `cliente_rentas_ibfk_1`
    FOREIGN KEY (`ClienteId`)
    REFERENCES `sistemarentasdominio`.`clientes` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `cliente_rentas_ibfk_2`
    FOREIGN KEY (`RentaId`)
    REFERENCES `sistemarentasdominio`.`rentas` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`solicitudes` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificacion de solicitudes',
  `FechaSolicitud` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de solicitud de producto',
  `NombreProductoAlternativo` VARCHAR(200) NULL DEFAULT NULL COMMENT 'Nombre alternativo del producto',
  `CantidadSolicitada` INT NULL DEFAULT '1' COMMENT 'Cantidad solicitada de solicitudes',
  `DescripcionNecesidad` TEXT NULL DEFAULT NULL COMMENT 'Descripcion de la solicitud',
  `EstadoSolicitud` ENUM('Nueva', 'EnProceso', 'Atendida', 'Cancelada') NULL DEFAULT 'Nueva' COMMENT 'Estado de la solicitud',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion',
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de actualizacion',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`cliente_solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`cliente_solicitudes` (
  `ClienteId` INT NOT NULL COMMENT 'Identificacion del cliente',
  `SolicitudId` INT NOT NULL COMMENT 'Identificacion de la solicitud',
  PRIMARY KEY (`ClienteId`, `SolicitudId`),
  INDEX `SolicitudId` (`SolicitudId` ASC) ,
  CONSTRAINT `cliente_solicitudes_ibfk_1`
    FOREIGN KEY (`ClienteId`)
    REFERENCES `sistemarentasdominio`.`clientes` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `cliente_solicitudes_ibfk_2`
    FOREIGN KEY (`SolicitudId`)
    REFERENCES `sistemarentasdominio`.`solicitudes` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`detallescotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`detallescotizacion` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identifiacion de los detalles de la cotizacion',
  `DescripcionItem` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Descripcion del item',
  `Cantidad` INT NOT NULL COMMENT 'Cantidad del item',
  `PrecioUnitario` DECIMAL(10,2) NOT NULL COMMENT 'Precio unitario del item',
  `Subtotal` DECIMAL(10,2) GENERATED ALWAYS AS ((`Cantidad` * `PrecioUnitario`)) VIRTUAL COMMENT 'Subtotal del item',
  `DescuentoPorcentaje` DECIMAL(5,2) NULL DEFAULT '0.00' COMMENT 'Porcentaje de descuento del item',
  `ImpuestosAplicables` DECIMAL(10,2) NULL DEFAULT NULL COMMENT 'Impuestos aplicables del item',
  `Notas` TEXT NULL DEFAULT NULL COMMENT 'Notas de la cotizacion',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion de la cotizacion',
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de actualizacion de la cotizacion',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`cotizacion_detallescotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`cotizacion_detallescotizacion` (
  `CotizacionId` INT NOT NULL COMMENT 'Identificacion de la cotizacion',
  `DetalleCotizacionId` INT NOT NULL COMMENT 'Identificacion del detalle de la cotizacion',
  PRIMARY KEY (`CotizacionId`, `DetalleCotizacionId`),
  INDEX `DetalleCotizacionId` (`DetalleCotizacionId` ASC) ,
  CONSTRAINT `cotizacion_detallescotizacion_ibfk_1`
    FOREIGN KEY (`CotizacionId`)
    REFERENCES `sistemarentasdominio`.`cotizaciones` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `cotizacion_detallescotizacion_ibfk_2`
    FOREIGN KEY (`DetalleCotizacionId`)
    REFERENCES `sistemarentasdominio`.`detallescotizacion` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`cotizacion_rentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`cotizacion_rentas` (
  `CotizacionId` INT NOT NULL COMMENT 'Identifiacion de la cotizacion',
  `RentaId` INT NOT NULL COMMENT 'Identifiacion de la renta',
  PRIMARY KEY (`CotizacionId`, `RentaId`),
  INDEX `RentaId` (`RentaId` ASC) ,
  CONSTRAINT `cotizacion_rentas_ibfk_1`
    FOREIGN KEY (`CotizacionId`)
    REFERENCES `sistemarentasdominio`.`cotizaciones` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `cotizacion_rentas_ibfk_2`
    FOREIGN KEY (`RentaId`)
    REFERENCES `sistemarentasdominio`.`rentas` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`productos` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identifiacion del producto',
  `Nombre` VARCHAR(150) NOT NULL COMMENT 'Nombre del producto',
  `Descripcion` TEXT NULL DEFAULT NULL COMMENT 'Descripcion del producto',
  `Marca` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Marca del producto',
  `Modelo` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Modelo del producto',
  `PrecioReferenciaRenta` DECIMAL(10,2) NULL DEFAULT NULL COMMENT 'Precio de referencia de la renta',
  `SKU` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Número de referencia único del producto',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion del producto',
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de actualizacion del producto',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `SKU` (`SKU` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`detallecotizacion_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`detallecotizacion_productos` (
  `DetalleCotizacionId` INT NOT NULL COMMENT 'Identifiacion del detalle de la cotizacion',
  `ProductoId` INT NOT NULL COMMENT 'Identifiacion dek producto',
  PRIMARY KEY (`DetalleCotizacionId`, `ProductoId`),
  INDEX `ProductoId` (`ProductoId` ASC) ,
  CONSTRAINT `detallecotizacion_productos_ibfk_1`
    FOREIGN KEY (`DetalleCotizacionId`)
    REFERENCES `sistemarentasdominio`.`detallescotizacion` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `detallecotizacion_productos_ibfk_2`
    FOREIGN KEY (`ProductoId`)
    REFERENCES `sistemarentasdominio`.`productos` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`detallesrenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`detallesrenta` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificacion de los detalles de la renta',
  `PrecioRentaItem` DECIMAL(10,2) NOT NULL COMMENT 'Precio del item en renta',
  `CondicionSalida` TEXT NULL DEFAULT NULL COMMENT 'Condicion de salida del item',
  `CondicionRegreso` TEXT NULL DEFAULT NULL COMMENT 'Condicion del ingreso del item',
  `Notas` TEXT NULL DEFAULT NULL COMMENT 'Notas del item',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion de la renta',
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de actualizacion de la renta',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`inventarioitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`inventarioitems` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificacion del item en inventario',
  `NumeroSerie` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Numero de serie del item',
  `EstadoItem` ENUM('Disponible', 'Rentado', 'EnMantenimiento', 'DeBaja') NOT NULL DEFAULT 'Disponible' COMMENT 'Estado del item',
  `FechaAdquisicion` DATE NULL DEFAULT NULL COMMENT 'Fecha de adquisicion del item',
  `CostoAdquisicion` DECIMAL(10,2) NULL DEFAULT NULL COMMENT 'Costo de adquisicion del item',
  `UbicacionFisica` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Ubicacion fisica del item',
  `Notas` TEXT NULL DEFAULT NULL COMMENT 'Notas del item',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion del  item',
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de actualizacion del item',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `NumeroSerie` (`NumeroSerie` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`detallerenta_inventarioitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`detallerenta_inventarioitems` (
  `DetalleRentaId` INT NOT NULL COMMENT 'Identificacion del detalle de la renta',
  `InventarioItemId` INT NOT NULL COMMENT 'Identificacion del item del inventario',
  PRIMARY KEY (`DetalleRentaId`, `InventarioItemId`),
  INDEX `InventarioItemId` (`InventarioItemId` ASC) ,
  CONSTRAINT `detallerenta_inventarioitems_ibfk_1`
    FOREIGN KEY (`DetalleRentaId`)
    REFERENCES `sistemarentasdominio`.`detallesrenta` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `detallerenta_inventarioitems_ibfk_2`
    FOREIGN KEY (`InventarioItemId`)
    REFERENCES `sistemarentasdominio`.`inventarioitems` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`devoluciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`devoluciones` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificacion de la devolucion',
  `FechaDevolucionProgramada` DATE NULL DEFAULT NULL COMMENT 'Fecha de la devolucion programada',
  `FechaDevolucionReal` DATETIME NULL DEFAULT NULL COMMENT 'Fecha de la devolucion real',
  `EstadoDevolucion` ENUM('Pendiente', 'EnProcesoInspeccion', 'Completa', 'IncompletaConProblemas') NULL DEFAULT 'Pendiente' COMMENT 'Estado de la devolucion',
  `PersonaRecibe` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Persona que recibe la devolucion',
  `NotasGenerales` TEXT NULL DEFAULT NULL COMMENT 'Notas generales de la devolucion',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion de la devolucion',
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de actualizacion de la devolucion',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`devolucion_inventarioitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`devolucion_inventarioitems` (
  `DevolucionId` INT NOT NULL COMMENT 'Identificacion de la devolucion ',
  `InventarioItemId` INT NOT NULL COMMENT 'Identificaion del item en inventario ',
  `CondicionAlRegresar` TEXT NULL DEFAULT NULL COMMENT 'Condicion del item al regresar',
  `RequiereMantenimiento` TINYINT(1) NULL DEFAULT '0' COMMENT 'Item que requiere mantenimiento',
  PRIMARY KEY (`DevolucionId`, `InventarioItemId`),
  INDEX `InventarioItemId` (`InventarioItemId` ASC) ,
  CONSTRAINT `devolucion_inventarioitems_ibfk_1`
    FOREIGN KEY (`DevolucionId`)
    REFERENCES `sistemarentasdominio`.`devoluciones` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `devolucion_inventarioitems_ibfk_2`
    FOREIGN KEY (`InventarioItemId`)
    REFERENCES `sistemarentasdominio`.`inventarioitems` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`mantenimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`mantenimientos` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identifiacion del mantenimiento ',
  `FechaInicio` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de inicio del mantenimiento',
  `FechaFinPrevista` DATE NULL DEFAULT NULL COMMENT 'Fecha final prevista del mantenimiento',
  `FechaFinReal` DATE NULL DEFAULT NULL COMMENT 'Fecha de final real del mantenimiento',
  `TipoMantenimiento` ENUM('Preventivo', 'Correctivo', 'Mejora') NULL DEFAULT 'Correctivo' COMMENT 'Tipo de mantenimiento',
  `DescripcionProblema` TEXT NULL DEFAULT NULL COMMENT 'Descripcion del problema',
  `DescripcionTrabajoRealizado` TEXT NULL DEFAULT NULL COMMENT 'Descripcion del trabajo realizado',
  `CostoEstimado` DECIMAL(10,2) NULL DEFAULT NULL COMMENT 'Costo estimado del mantenimiento',
  `CostoReal` DECIMAL(10,2) NULL DEFAULT NULL COMMENT 'Costo real del mantenimiento',
  `EstadoMantenimiento` ENUM('Programado', 'EnProceso', 'Finalizado', 'Cancelado') NULL DEFAULT 'Programado' COMMENT 'Estado del mantenimiento',
  `Responsable` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Responsable del mantenimiento',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion del mantenimiento',
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de actualizacion del mantenimiento',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`devolucionitem_mantenimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`devolucionitem_mantenimientos` (
  `DevolucionId` INT NOT NULL COMMENT 'Identifiacion de la devolucion',
  `InventarioItemId` INT NOT NULL COMMENT 'Identifiacion del item en inventario',
  `MantenimientoId` INT NOT NULL COMMENT 'Identificacion del mantenimiento',
  PRIMARY KEY (`DevolucionId`, `InventarioItemId`, `MantenimientoId`),
  INDEX `InventarioItemId` (`InventarioItemId` ASC) ,
  INDEX `MantenimientoId` (`MantenimientoId` ASC) ,
  CONSTRAINT `devolucionitem_mantenimientos_ibfk_1`
    FOREIGN KEY (`DevolucionId`)
    REFERENCES `sistemarentasdominio`.`devoluciones` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `devolucionitem_mantenimientos_ibfk_2`
    FOREIGN KEY (`InventarioItemId`)
    REFERENCES `sistemarentasdominio`.`inventarioitems` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `devolucionitem_mantenimientos_ibfk_3`
    FOREIGN KEY (`MantenimientoId`)
    REFERENCES `sistemarentasdominio`.`mantenimientos` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`entregas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`entregas` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificacion de la entraga',
  `FechaEnvio` DATETIME NULL DEFAULT NULL COMMENT 'Fecha de envio de la entrega',
  `CompaniaEnvio` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Compañia de envio de la entrega',
  `NumeroGuia` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Numero de guia de la entrega',
  `EstadoEntrega` ENUM('Programada', 'EnTransito', 'Entregada', 'Fallida') NULL DEFAULT 'Programada' COMMENT 'Estado de la entrega ',
  `Notas` TEXT NULL DEFAULT NULL COMMENT 'Notas de la entrega',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion de la entrega',
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de actualizacion de la entrega',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`entrega_direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`entrega_direcciones` (
  `EntregaId` INT NOT NULL COMMENT 'Identificacion de la entrega',
  `DireccionId` INT NOT NULL COMMENT 'Identificacion de la entrega',
  PRIMARY KEY (`EntregaId`, `DireccionId`),
  INDEX `DireccionId` (`DireccionId` ASC) ,
  CONSTRAINT `entrega_direcciones_ibfk_1`
    FOREIGN KEY (`EntregaId`)
    REFERENCES `sistemarentasdominio`.`entregas` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `entrega_direcciones_ibfk_2`
    FOREIGN KEY (`DireccionId`)
    REFERENCES `sistemarentasdominio`.`direcciones` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`entrega_inventarioitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`entrega_inventarioitems` (
  `EntregaId` INT NOT NULL COMMENT 'Identificacion de la entrega',
  `InventarioItemId` INT NOT NULL COMMENT 'Identificacion del item en el inventario',
  PRIMARY KEY (`EntregaId`, `InventarioItemId`),
  INDEX `InventarioItemId` (`InventarioItemId` ASC) ,
  CONSTRAINT `entrega_inventarioitems_ibfk_1`
    FOREIGN KEY (`EntregaId`)
    REFERENCES `sistemarentasdominio`.`entregas` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `entrega_inventarioitems_ibfk_2`
    FOREIGN KEY (`InventarioItemId`)
    REFERENCES `sistemarentasdominio`.`inventarioitems` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`inventarioitem_mantenimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`inventarioitem_mantenimientos` (
  `InventarioItemId` INT NOT NULL COMMENT 'Identificacion del item en inventario ',
  `MantenimientoId` INT NOT NULL COMMENT 'Identifiacion del mantenimiento',
  PRIMARY KEY (`InventarioItemId`, `MantenimientoId`),
  INDEX `MantenimientoId` (`MantenimientoId` ASC) ,
  CONSTRAINT `inventarioitem_mantenimientos_ibfk_1`
    FOREIGN KEY (`InventarioItemId`)
    REFERENCES `sistemarentasdominio`.`inventarioitems` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `inventarioitem_mantenimientos_ibfk_2`
    FOREIGN KEY (`MantenimientoId`)
    REFERENCES `sistemarentasdominio`.`mantenimientos` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`producto_inventarioitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`producto_inventarioitems` (
  `ProductoId` INT NOT NULL COMMENT 'Identifiacion del producto',
  `InventarioItemId` INT NOT NULL COMMENT 'Identifiacion del item en inventario',
  PRIMARY KEY (`ProductoId`, `InventarioItemId`),
  INDEX `InventarioItemId` (`InventarioItemId` ASC) ,
  CONSTRAINT `producto_inventarioitems_ibfk_1`
    FOREIGN KEY (`ProductoId`)
    REFERENCES `sistemarentasdominio`.`productos` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `producto_inventarioitems_ibfk_2`
    FOREIGN KEY (`InventarioItemId`)
    REFERENCES `sistemarentasdominio`.`inventarioitems` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`proveedores` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificacion del proveedor',
  `NombreEmpresa` VARCHAR(200) NOT NULL COMMENT 'Nombre de la empresa del proveedor',
  `RFC` VARCHAR(13) NULL DEFAULT NULL COMMENT 'Registro Único Tributario del proveedor',
  `NombreContacto` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Nombre de contacto del proveedor',
  `TelefonoContacto` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Telefono de contacto del proveedor',
  `CorreoContacto` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Correo de contacto del proveedor',
  `EstadoProveedor` ENUM('Activo', 'Inactivo') NULL DEFAULT 'Activo' COMMENT 'Estado del proveedor',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion del proveedor',
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de actualizacion del proveedor',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `NombreEmpresa` (`NombreEmpresa` ASC) ,
  UNIQUE INDEX `RFC` (`RFC` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`proveedor_cotizaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`proveedor_cotizaciones` (
  `ProveedorId` INT NOT NULL COMMENT 'Identificacion del proveedor',
  `CotizacionId` INT NOT NULL COMMENT 'Identificacion de la cotizacion',
  PRIMARY KEY (`ProveedorId`, `CotizacionId`),
  INDEX `CotizacionId` (`CotizacionId` ASC) ,
  CONSTRAINT `proveedor_cotizaciones_ibfk_1`
    FOREIGN KEY (`ProveedorId`)
    REFERENCES `sistemarentasdominio`.`proveedores` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `proveedor_cotizaciones_ibfk_2`
    FOREIGN KEY (`CotizacionId`)
    REFERENCES `sistemarentasdominio`.`cotizaciones` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`proveedor_direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`proveedor_direcciones` (
  `ProveedorId` INT NOT NULL COMMENT 'Identificacion del proveedor',
  `DireccionId` INT NOT NULL COMMENT 'Identificacion de la direccion',
  `EsPrincipal` TINYINT(1) NULL DEFAULT '1' COMMENT 'Principal de la direccion',
  PRIMARY KEY (`ProveedorId`, `DireccionId`),
  INDEX `DireccionId` (`DireccionId` ASC) ,
  CONSTRAINT `proveedor_direcciones_ibfk_1`
    FOREIGN KEY (`ProveedorId`)
    REFERENCES `sistemarentasdominio`.`proveedores` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `proveedor_direcciones_ibfk_2`
    FOREIGN KEY (`DireccionId`)
    REFERENCES `sistemarentasdominio`.`direcciones` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`renta_detallesrenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`renta_detallesrenta` (
  `RentaId` INT NOT NULL COMMENT 'Identificacion de la renta',
  `DetalleRentaId` INT NOT NULL COMMENT 'identificacion del detalle de la renta ',
  PRIMARY KEY (`RentaId`, `DetalleRentaId`),
  INDEX `DetalleRentaId` (`DetalleRentaId` ASC) ,
  CONSTRAINT `renta_detallesrenta_ibfk_1`
    FOREIGN KEY (`RentaId`)
    REFERENCES `sistemarentasdominio`.`rentas` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `renta_detallesrenta_ibfk_2`
    FOREIGN KEY (`DetalleRentaId`)
    REFERENCES `sistemarentasdominio`.`detallesrenta` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`renta_devoluciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`renta_devoluciones` (
  `RentaId` INT NOT NULL COMMENT 'Identificacion de la renta',
  `DevolucionId` INT NOT NULL COMMENT 'Identificacion de la devolucion',
  PRIMARY KEY (`RentaId`, `DevolucionId`),
  INDEX `DevolucionId` (`DevolucionId` ASC) ,
  CONSTRAINT `renta_devoluciones_ibfk_1`
    FOREIGN KEY (`RentaId`)
    REFERENCES `sistemarentasdominio`.`rentas` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `renta_devoluciones_ibfk_2`
    FOREIGN KEY (`DevolucionId`)
    REFERENCES `sistemarentasdominio`.`devoluciones` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`renta_entregas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`renta_entregas` (
  `RentaId` INT NOT NULL COMMENT 'Identificacion de la renta',
  `EntregaId` INT NOT NULL COMMENT 'Identificacion de la entrega',
  PRIMARY KEY (`RentaId`, `EntregaId`),
  INDEX `EntregaId` (`EntregaId` ASC) ,
  CONSTRAINT `renta_entregas_ibfk_1`
    FOREIGN KEY (`RentaId`)
    REFERENCES `sistemarentasdominio`.`rentas` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `renta_entregas_ibfk_2`
    FOREIGN KEY (`EntregaId`)
    REFERENCES `sistemarentasdominio`.`entregas` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`roles` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificacion del rol',
  `Codigo` VARCHAR(50) NOT NULL COMMENT 'Codigo del rol',
  `Nombre` VARCHAR(100) NOT NULL COMMENT 'Nombre del rol',
  `Descripcion` TEXT NULL DEFAULT NULL COMMENT 'Descripcion del rol',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion del rol',
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'fecha de actualizacion del rol',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Codigo` (`Codigo` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`solicitud_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`solicitud_categorias` (
  `SolicitudId` INT NOT NULL COMMENT 'Identificacion de la solicitud',
  `CategoriaId` INT NOT NULL COMMENT 'Identificacion de la categoria',
  PRIMARY KEY (`SolicitudId`, `CategoriaId`),
  INDEX `CategoriaId` (`CategoriaId` ASC) ,
  CONSTRAINT `solicitud_categorias_ibfk_1`
    FOREIGN KEY (`SolicitudId`)
    REFERENCES `sistemarentasdominio`.`solicitudes` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `solicitud_categorias_ibfk_2`
    FOREIGN KEY (`CategoriaId`)
    REFERENCES `sistemarentasdominio`.`categorias` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`solicitud_cotizaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`solicitud_cotizaciones` (
  `SolicitudId` INT NOT NULL COMMENT 'Identificacion de la solicitud',
  `CotizacionId` INT NOT NULL COMMENT 'Identificacion de la cotizacion',
  PRIMARY KEY (`SolicitudId`, `CotizacionId`),
  INDEX `CotizacionId` (`CotizacionId` ASC) ,
  CONSTRAINT `solicitud_cotizaciones_ibfk_1`
    FOREIGN KEY (`SolicitudId`)
    REFERENCES `sistemarentasdominio`.`solicitudes` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `solicitud_cotizaciones_ibfk_2`
    FOREIGN KEY (`CotizacionId`)
    REFERENCES `sistemarentasdominio`.`cotizaciones` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`solicitud_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`solicitud_productos` (
  `SolicitudId` INT NOT NULL COMMENT 'Identificacion de la solicitud',
  `ProductoId` INT NOT NULL COMMENT 'Identificacion del producto',
  PRIMARY KEY (`SolicitudId`, `ProductoId`),
  INDEX `ProductoId` (`ProductoId` ASC) ,
  CONSTRAINT `solicitud_productos_ibfk_1`
    FOREIGN KEY (`SolicitudId`)
    REFERENCES `sistemarentasdominio`.`solicitudes` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `solicitud_productos_ibfk_2`
    FOREIGN KEY (`ProductoId`)
    REFERENCES `sistemarentasdominio`.`productos` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`solicitud_subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`solicitud_subcategorias` (
  `SolicitudId` INT NOT NULL COMMENT 'Identificacion de la solicitud',
  `SubcategoriaId` INT NOT NULL COMMENT 'Identificacion de la subcategoria',
  PRIMARY KEY (`SolicitudId`, `SubcategoriaId`),
  INDEX `SubcategoriaId` (`SubcategoriaId` ASC) ,
  CONSTRAINT `solicitud_subcategorias_ibfk_1`
    FOREIGN KEY (`SolicitudId`)
    REFERENCES `sistemarentasdominio`.`solicitudes` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `solicitud_subcategorias_ibfk_2`
    FOREIGN KEY (`SubcategoriaId`)
    REFERENCES `sistemarentasdominio`.`subcategorias` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`subcategoria_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`subcategoria_productos` (
  `SubcategoriaId` INT NOT NULL COMMENT 'Identificacion de la subcategoria',
  `ProductoId` INT NOT NULL COMMENT 'Identifiacion del producto',
  PRIMARY KEY (`SubcategoriaId`, `ProductoId`),
  INDEX `ProductoId` (`ProductoId` ASC) ,
  CONSTRAINT `subcategoria_productos_ibfk_1`
    FOREIGN KEY (`SubcategoriaId`)
    REFERENCES `sistemarentasdominio`.`subcategorias` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `subcategoria_productos_ibfk_2`
    FOREIGN KEY (`ProductoId`)
    REFERENCES `sistemarentasdominio`.`productos` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`usuarios` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificacion del usuario ',
  `NombreUsuario` VARCHAR(100) NOT NULL COMMENT 'Nombre del usuario ',
  `PasswordHash` VARCHAR(255) NOT NULL COMMENT 'Contraseña hash del usuario',
  `NombreCompleto` VARCHAR(200) NULL DEFAULT NULL COMMENT 'Nombre completo del usuario',
  `Email` VARCHAR(100) NOT NULL COMMENT 'Correo del usuario',
  `Telefono` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Telefono del usuario',
  `Departamento` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Departamento del usuario',
  `Estado` ENUM('Activo', 'Inactivo', 'Bloqueado') NULL DEFAULT 'Activo' COMMENT 'Estado del usuario ',
  `CreatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion del usuario',
  `UpdatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de actualizacion del usuario',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `NombreUsuario` (`NombreUsuario` ASC) ,
  UNIQUE INDEX `Email` (`Email` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistemarentasdominio`.`usuario_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemarentasdominio`.`usuario_roles` (
  `UsuarioId` INT NOT NULL COMMENT 'Identificacion del usuario',
  `RolId` INT NOT NULL COMMENT 'Identificacion del rol',
  PRIMARY KEY (`UsuarioId`, `RolId`),
  INDEX `RolId` (`RolId` ASC) ,
  CONSTRAINT `usuario_roles_ibfk_1`
    FOREIGN KEY (`UsuarioId`)
    REFERENCES `sistemarentasdominio`.`usuarios` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `usuario_roles_ibfk_2`
    FOREIGN KEY (`RolId`)
    REFERENCES `sistemarentasdominio`.`roles` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
